- hosts: all
  vars:
    path: /home/ec2-user
  remote_user: ec2-user
  tasks:
    - name: Create a file
      file:
        path: '{{ app_path }}/created_by_ansible'
        owner: ec2-user
        group: ec2-user
        mode: 744
        state: file
